homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name= 'contact'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'Home.html')

def about(request):
    return render(request, 'About.html')

def education(request):
    return render(request, 'Education.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

homepage/templates/About.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="About">
        <div id="About-title">
            <img src="{% static 'images/Ocit.png' %}" alt="">

            <h1>About Me</h1>
            <div id="rectangle1"></div>
            <p>Rasyid atau yang biasa disapa dengan Ocit merupakan seorang mahasiswa Fasilkom UI tahun kedua. Ia merupakan anak yang sangat senang mempelajari hal baru. Ocit juga hobi berenang loh, giginya patah saat sedang latihan loncat untuk lomba pertamanya. Dia juga senang membantu orang lain sampai lupa dengan dirinya sendiri.</p>
        </div>
    </div>
</body>
</html>

homepage/templates/Education.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="Education">
        <div id="Education-title">
            <h1>Education & Experience</h1>
            <div id="rectangle2"></div>
        </div>

        <div id="riwayat">
            <ul>
                <li>SDIT Nurul Falah</li>
                <li>SMP Negeri 1 Kota Bekasi</li>
                <li>SMA Negeri 5 Kota Bandung</li>
                <li>Universitas Indonesia<p id="keterangan">Fakultas Ilmu Komputer</p></li>
            </ul>
        </div>

        <div id="pengalaman">
            <ul>
                <li>ScaleUp.id (Now Levilo.id)<p id="keterangan">Internship as Video Editor & Graphic Designer</p></li>
            </ul>
        </div>
    </div>
</body>
</html>

homepage/templates/Home.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div class="Home">
        <div id="Home-overlay">
            <p class="slideup">Hi,</p>
            <div id = "imocit">
                <h1 id=ocit>I Am Rasyid.</h1>
            </div>
            <div class="social">
                <ul>
                    <a href="https://www.instagram.com/siidrasyid" target="_blank"><li><i class="fab fa-instagram" aria-hidden="true"></i></li></a>
                    <a href="https://www.facebook.com/SSHBangOcit" target="_blank"><li><i class="fab fa-facebook-f" aria-hidden="true"></i></li></a>
                    <a href="https://www.linkedin.com/in/muhammadrasyid22/" target="_blank"><li><i class="fab fa-linkedin-in" aria-hidden="true"></i></li></a>
                    <a href="https://line.me/ti/p/n3DUuSuAx5" target="_blank"><li><i class="fab fa-line" aria-hidden="true"></i></li></a>
                </ul>
            </div> 
        </div>
        
    </div>

    
</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="Contact">
        <h1>Contact Me</h1>
        <div id="rectangle3"></div>
        <div class="social">
            <ul>
                <a href="https://www.instagram.com/siidrasyid" target="_blank"><li><i class="fab fa-instagram" aria-hidden="true"></i></li></a>
                <a href="https://www.facebook.com/SSHBangOcit" target="_blank"><li><i class="fab fa-facebook-f" aria-hidden="true"></i></li></a>
                <a href="https://www.linkedin.com/in/muhammadrasyid22/" target="_blank"><li><i class="fab fa-linkedin-in" aria-hidden="true"></i></li></a>
                <a href="https://line.me/ti/p/n3DUuSuAx5" target="_blank"><li><i class="fab fa-line" aria-hidden="true"></i></li></a>
            </ul>
        </div>

    </div>
</body>
</html>

homepage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="Gallery">
        <h1>Portofolio</h1>
        <div id="rectangle4"></div>
        <div class="Photo">
            <img class="photo1" src="{% static 'images/1.png' %}" width="400" height="400">
            <img class="photo2" src="{% static 'images/2.png' %}" width="400" height="400">
            <img class="photo3" src="{% static 'images/3.png' %}" width="400" height="400">
        </div>
    </div>
</body>
</html>